// packages/shelter-docs/demos/src/demos/SwitchDemo.tsx
import { createSignal } from "solid-js";
import { Switch, Text } from "@uwu/shelter-ui";

export default function SwitchDemo() {
  const [checked, setChecked] = createSignal(false);
  return (
    <div style={{ display: "flex", gap: "16px", "align-items": "center" }}>
      <Switch checked={checked()} onChange={setChecked} />
      <Text>{checked() ? "On" : "Off"}</Text>
    </div>
  );
}

// packages/shelter-docs/docs/components/shelter-ui-demos/SwitchDemo.vue
<script setup lang="jsx">
import {createSignal, onCleanup} from "solid-js";
import {Switch} from "@uwu/shelter-ui";
import MountBox from "../MountBox.vue";

function comp() {
  const [sig, setSig] = createSignal(false);

  const intcode = setInterval(() => setSig(v => !v), 3000);
  onCleanup(() => clearInterval(intcode))

  return <Switch checked={sig()} onChange={setSig} />;
}
</script>

<template>
  <MountBox :component="comp" />
</template>
